微服务网关: src/config.c File Reference
config.c File Reference
#include "gateway.h"
Functions
int load_gateway_config (const char *config_file)
加载网关配置文件
int load_service_config (const char *config_file)
加载服务配置文件
Function Documentation
load_gateway_config()
int load_gateway_config (const char * config_file)
加载网关配置文件
从 JSON 配置文件加载网关配置。
Parameters
config_file 配置文件路径
Returns
int 0 表示成功，-1 表示失败
Definition at line 4 of file config.c.
References DEFAULT_HEALTH_CHECK_INTERVAL, g_gateway_config, LOG_LEVEL_DEBUG, LOG_LEVEL_ERROR, LOG_LEVEL_INFO, log_level_str(), and LOG_LEVEL_WARN.
Referenced by main().
load_service_config()
int load_service_config (const char * config_file)
加载服务配置文件
从 JSON 配置文件加载服务注册信息。
Parameters
config_file 配置文件路径
Returns
int 0 表示成功，-1 表示失败
Definition at line 190 of file config.c.
References PROTOCOL_HTTP, PROTOCOL_HTTPS, and service_register_with_ipv6().