微服务网关: include/gateway.h File Reference
gateway.h File Reference
微服务网关核心头文件
#include <uv.h>
#include <llhttp.h>
#include <curl/curl.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <pthread.h>
#include <cJSON.h>
#include <stdint.h>
#include <time.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <unistd.h>
#include <sys/syscall.h>
Data Structures
struct observability_config_t
可观测性配置结构
struct ip_address_t
IP 地址结构
struct service_instance_t
服务实例信息
struct service_t
服务定义结构
struct service_registry_t
服务注册表
struct mem_pool_t
内存池结构
struct client_ctx_t
客户端上下文结构
struct write_ctx_t
写入上下文结构
struct proxy_request_t
代理请求上下文
struct employee_t
模拟员工数据（示例 API 用）
struct gateway_config_t
网关配置结构
Macros
#define gettid()
#define POOL_SIZE 8192
#define MAX_SERVICES 64
#define MAX_SERVICE_INSTANCES 16
#define SERVICE_NAME_LEN 64
#define SERVICE_HOST_LEN 256
#define DEFAULT_HEALTH_CHECK_INTERVAL 5000
Enumerations
enum log_level_t { LOG_LEVEL_DEBUG = 0 , LOG_LEVEL_INFO , LOG_LEVEL_WARN , LOG_LEVEL_ERROR }
日志级别枚举
enum protocol_t { PROTOCOL_HTTP , PROTOCOL_HTTPS }
协议类型枚举
enum service_health_t { SERVICE_HEALTHY , SERVICE_UNHEALTHY , SERVICE_UNKNOWN }
服务实例健康状态
Functions
void on_new_connection (uv_stream_t *server, int status)
新连接回调函数
void on_write_completed (uv_write_t *req, int status)
写入完成回调函数
void route_request (client_ctx_t *client)
路由请求处理函数
void send_response (client_ctx_t *client, int status_code, const char *content_type, char *body_to_send)
发送 HTTP 响应
void handle_get_employees (client_ctx_t *client)
获取员工列表处理器
void handle_get_services (client_ctx_t *client)
获取服务列表处理器
void handle_service_register (client_ctx_t *client)
服务注册处理器
void handle_service_unregister (client_ctx_t *client)
服务注销处理器
char * get_query_param (client_ctx_t *ctx, const char *key)
获取查询参数
void * pool_alloc (client_ctx_t *ctx, size_t size)
从内存池分配内存
int parse_ip_address (const char *host, ip_address_t *addr)
解析 IP 地址
void log_request (log_level_t level, client_ctx_t *ctx, const char *event, const char *format,...)
记录请求日志（通用接口）
void log_debug (client_ctx_t *ctx, const char *event, const char *format,...)
记录调试日志
void log_info (client_ctx_t *ctx, const char *event, const char *format,...)
记录信息日志
void log_warn (client_ctx_t *ctx, const char *event, const char *format,...)
记录警告日志
void log_error (client_ctx_t *ctx, const char *event, const char *format,...)
记录错误日志
uint64_t get_time_nanoseconds (void)
获取纳秒级时间戳
void metrics_init (void)
初始化指标系统
void metrics_server_start (void)
启动指标服务器
void metrics_request_start (client_ctx_t *ctx)
记录请求开始
void metrics_request_end (client_ctx_t *ctx, int status_code, double duration_sec)
记录请求完成
void metrics_upstream_duration (double duration_sec)
记录上游服务延迟
void metrics_generate_output (char *buffer, size_t buffer_size)
生成 Prometheus 格式输出
void tracing_init_context (client_ctx_t *ctx, const char *incoming_traceparent)
初始化追踪上下文
void tracing_export_span (client_ctx_t *ctx, const char *operation, double duration_ms)
导出追踪跨度
void tracing_get_outgoing_traceparent (client_ctx_t *ctx, char *buffer, size_t size)
获取传出追踪上下文
void tracing_add_event (client_ctx_t *ctx, const char *event_name, const char *attributes)
添加追踪事件
void service_registry_init (void)
初始化服务注册表
int service_register (const char *name, const char *path_prefix, const char *host, int port, protocol_t protocol, const char *health_endpoint, int verify_ssl)
注册服务（简化版）
int service_register_with_ipv6 (const char *name, const char *description, const char *path_prefix, const char *host, int port, protocol_t protocol, const char *health_endpoint, int verify_ssl, int is_ipv6)
注册服务（完整版，支持 IPv6）
int service_deregister (const char *name, const char *host, int port)
注销服务
service_t * service_find_by_path (const char *path)
根据路径查找服务
service_instance_t * service_select_instance (service_t *service)
选择服务实例（负载均衡）
void start_health_checker (void)
启动健康检查器
void forward_to_service (client_ctx_t *client, service_instance_t *instance)
转发请求到后端服务
int load_service_config (const char *config_file)
加载服务配置文件
int init_tcp_server_ipv6 (uv_loop_t *loop, uv_tcp_t *server, const char *addr, int port)
TCP 服务器初始化（支持 IPv6）
int load_gateway_config (const char *config_file)
加载网关配置文件
Variables
gateway_config_t g_gateway_config
service_registry_t g_registry
Detailed Description
微服务网关核心头文件
定义了网关的所有核心数据结构、类型和函数声明。 包括网络层、路由层、代理层、健康检查、可观测性等模块。
Author
乔水
Date
2026-03-25
Version
1.0.0
Definition in file gateway.h.
Macro Definition Documentation
DEFAULT_HEALTH_CHECK_INTERVAL
#define DEFAULT_HEALTH_CHECK_INTERVAL 5000
Definition at line 53 of file gateway.h.
Referenced by load_gateway_config().
gettid
#define gettid ()
Value:
syscall(__NR_gettid)
Definition at line 45 of file gateway.h.
Referenced by worker_thread().
MAX_SERVICE_INSTANCES
#define MAX_SERVICE_INSTANCES 16
Definition at line 50 of file gateway.h.
Referenced by service_register_with_ipv6().
MAX_SERVICES
#define MAX_SERVICES 64
Definition at line 49 of file gateway.h.
Referenced by service_register_with_ipv6().
POOL_SIZE
#define POOL_SIZE 8192
Definition at line 48 of file gateway.h.
Referenced by pool_alloc().
SERVICE_HOST_LEN
#define SERVICE_HOST_LEN 256
Definition at line 52 of file gateway.h.
Referenced by service_register_with_ipv6().
SERVICE_NAME_LEN
#define SERVICE_NAME_LEN 64
Definition at line 51 of file gateway.h.
Referenced by service_register_with_ipv6().
Enumeration Type Documentation
log_level_t
enum log_level_t
日志级别枚举
定义系统支持的日志级别，用于控制日志输出的详细程度。
Enumerator
LOG_LEVEL_DEBUG
调试级别：最详细的输出
LOG_LEVEL_INFO
信息级别：正常运行日志
LOG_LEVEL_WARN
警告级别：潜在问题告警
LOG_LEVEL_ERROR
错误级别：严重错误记录
Definition at line 59 of file gateway.h.
protocol_t
enum protocol_t
协议类型枚举
定义后端服务支持的协议类型。
Enumerator
PROTOCOL_HTTP
HTTP 协议
PROTOCOL_HTTPS
HTTPS 协议（加密传输）
Definition at line 95 of file gateway.h.
service_health_t
enum service_health_t
服务实例健康状态
定义后端服务实例的健康检查状态。
Enumerator
SERVICE_HEALTHY
健康：服务正常响应
SERVICE_UNHEALTHY
不健康：服务异常或无响应
SERVICE_UNKNOWN
未知：尚未进行健康检查
Definition at line 105 of file gateway.h.
Function Documentation
forward_to_service()
void forward_to_service (client_ctx_t * client, service_instance_t * instance)
转发请求到后端服务
将客户端请求异步转发到选中的后端服务实例。
Parameters
client 客户端上下文
instance 目标服务实例
Definition at line 55 of file proxy.c.
References client_ctx_t::body_buffer, client_ctx_t::body_len, service_instance_t::ca_cert_path, proxy_request_t::client, proxy_request_t::curl, g_gateway_config, get_time_nanoseconds(), client_ctx_t::handle, proxy_request_t::headers, service_instance_t::health, service_instance_t::host, service_instance_t::ip_addr, ip_address_t::is_ipv6, client_ctx_t::is_sampled, log_debug(), log_error(), log_info(), metrics_upstream_duration(), client_ctx_t::parser, service_instance_t::port, service_instance_t::protocol, PROTOCOL_HTTPS, proxy_complete_callback(), proxy_write_callback(), proxy_request_t::response_data, send_response(), SERVICE_UNHEALTHY, proxy_request_t::status_code, tracing_get_outgoing_traceparent(), client_ctx_t::url, and service_instance_t::verify_ssl.
Referenced by route_request().
get_query_param()
char * get_query_param (client_ctx_t * ctx, const char * key)
获取查询参数
从 URL 查询字符串中提取指定参数的值。
Parameters
ctx 客户端上下文
key 参数名
Returns
char* 参数值（栈内存，生命周期同请求）
Definition at line 24 of file utils.c.
References pool_alloc(), and client_ctx_t::url.
Referenced by handle_get_employees().
get_time_nanoseconds()
uint64_t get_time_nanoseconds (void)
获取纳秒级时间戳
Returns
uint64_t 纳秒级时间戳（相对于系统启动时间）
Definition at line 33 of file logger.c.
Referenced by forward_to_service(), on_new_connection(), and on_write_completed().
handle_get_employees()
void handle_get_employees (client_ctx_t * client)
获取员工列表处理器
处理 GET /api/employees 请求，返回模拟的员工数据。
Parameters
client 客户端上下文
获取员工列表处理器
Definition at line 324 of file router.c.
References db_count, employee_t::dept, employee_db, get_query_param(), employee_t::id, employee_t::name, employee_t::salary, and send_response().
handle_get_services()
void handle_get_services (client_ctx_t * client)
获取服务列表处理器
处理 GET /services 请求，返回已注册的服务列表。
Parameters
client 客户端上下文
获取服务列表处理器
Definition at line 137 of file router.c.
References service_t::description, g_registry, service_instance_t::health, service_t::health_endpoint, service_instance_t::host, service_t::instance_count, service_t::instances, service_instance_t::ip_addr, ip_address_t::is_ipv6, service_t::lock, service_t::name, service_t::path_prefix, service_instance_t::port, service_instance_t::protocol, PROTOCOL_HTTPS, service_instance_t::request_count, send_response(), SERVICE_HEALTHY, SERVICE_UNHEALTHY, and service_instance_t::verify_ssl.
Referenced by route_request().
handle_service_register()
void handle_service_register (client_ctx_t * client)
服务注册处理器
处理 POST /services/register 请求，注册新的服务实例。
Parameters
client 客户端上下文
服务注册处理器
Definition at line 197 of file router.c.
References client_ctx_t::body_buffer, PROTOCOL_HTTP, PROTOCOL_HTTPS, send_response(), and service_register_with_ipv6().
Referenced by route_request().
handle_service_unregister()
void handle_service_unregister (client_ctx_t * client)
服务注销处理器
处理 POST /services/unregister 请求，注销服务实例。
Parameters
client 客户端上下文
服务注销处理器
Definition at line 273 of file router.c.
References client_ctx_t::body_buffer, send_response(), and service_deregister().
Referenced by route_request().
init_tcp_server_ipv6()
int init_tcp_server_ipv6 (uv_loop_t * loop, uv_tcp_t * server, const char * addr, int port)
TCP 服务器初始化（支持 IPv6）
初始化 TCP 服务器，优先使用 IPv6，失败则回退到 IPv4。
Parameters
loop libuv 事件循环
server TCP 服务器句柄
addr 监听地址
port 监听端口
Returns
int 0 表示成功，-1 表示失败
Definition at line 5 of file main.c.
References g_gateway_config.
Referenced by worker_thread().
load_gateway_config()
int load_gateway_config (const char * config_file)
加载网关配置文件
从 JSON 配置文件加载网关配置。
Parameters
config_file 配置文件路径
Returns
int 0 表示成功，-1 表示失败
Definition at line 4 of file config.c.
References DEFAULT_HEALTH_CHECK_INTERVAL, g_gateway_config, LOG_LEVEL_DEBUG, LOG_LEVEL_ERROR, LOG_LEVEL_INFO, log_level_str(), and LOG_LEVEL_WARN.
Referenced by main().
load_service_config()
int load_service_config (const char * config_file)
加载服务配置文件
从 JSON 配置文件加载服务注册信息。
Parameters
config_file 配置文件路径
Returns
int 0 表示成功，-1 表示失败
Definition at line 190 of file config.c.
References PROTOCOL_HTTP, PROTOCOL_HTTPS, and service_register_with_ipv6().
log_debug()
void log_debug (client_ctx_t * ctx, const char * event, const char * format, ...)
记录调试日志
Parameters
ctx 客户端上下文
event 事件名称
format 格式化字符串
Definition at line 204 of file logger.c.
References LOG_LEVEL_DEBUG, and log_request().
Referenced by export_to_http_collector(), forward_to_service(), on_client_close(), tracing_add_event(), and tracing_init_context().
log_error()
void log_error (client_ctx_t * ctx, const char * event, const char * format, ...)
记录错误日志
Parameters
ctx 客户端上下文
event 事件名称
format 格式化字符串
Definition at line 234 of file logger.c.
References LOG_LEVEL_ERROR, and log_request().
Referenced by forward_to_service().
log_info()
void log_info (client_ctx_t * ctx, const char * event, const char * format, ...)
记录信息日志
Parameters
ctx 客户端上下文
event 事件名称
format 格式化字符串
Definition at line 214 of file logger.c.
References LOG_LEVEL_INFO, and log_request().
Referenced by forward_to_service(), main(), metrics_init(), on_message_complete(), and on_write_completed().
log_request()
void log_request (log_level_t level, client_ctx_t * ctx, const char * event, const char * format, ...)
记录请求日志（通用接口）
根据配置的日志级别和格式，记录请求相关的日志。 支持 JSON 和文本两种格式。
Parameters
level 日志级别
ctx 客户端上下文
event 事件名称
format 格式化字符串
Definition at line 106 of file logger.c.
References escape_json_string(), g_gateway_config, get_timestamp_iso(), log_level_str(), client_ctx_t::request_id, client_ctx_t::span_id, and client_ctx_t::trace_id.
Referenced by log_debug(), log_error(), log_info(), and log_warn().
log_warn()
void log_warn (client_ctx_t * ctx, const char * event, const char * format, ...)
记录警告日志
Parameters
ctx 客户端上下文
event 事件名称
format 格式化字符串
Definition at line 224 of file logger.c.
References LOG_LEVEL_WARN, and log_request().
metrics_generate_output()
void metrics_generate_output (char * buffer, size_t buffer_size)
生成 Prometheus 格式输出
将所有指标格式化为 Prometheus 文本格式。
Parameters
buffer 输出缓冲区
buffer_size 缓冲区大小
Definition at line 199 of file metrics.c.
References APPEND, http_request_duration_seconds, http_request_errors_total, http_requests_in_flight, http_requests_total, and http_upstream_duration_seconds.
Referenced by metrics_read_cb().
metrics_init()
void metrics_init (void)
初始化指标系统
初始化所有 Prometheus 指标的初始值。
Definition at line 150 of file metrics.c.
References g_gateway_config, init_metrics(), and log_info().
Referenced by main().
metrics_request_end()
void metrics_request_end (client_ctx_t * ctx, int status_code, double duration_sec)
记录请求完成
在请求完成时调用，更新请求总数、延迟直方图等指标。
Parameters
ctx 客户端上下文
status_code HTTP 状态码
duration_sec 请求持续时间（秒）
Definition at line 171 of file metrics.c.
References counter_dec(), counter_inc(), g_gateway_config, histogram_observe(), http_request_duration_seconds, http_request_errors_total, and http_requests_in_flight.
Referenced by on_write_completed().
metrics_request_start()
void metrics_request_start (client_ctx_t * ctx)
记录请求开始
在请求开始时调用，记录开始时间和初始状态。
Parameters
ctx 客户端上下文
Definition at line 160 of file metrics.c.
References counter_inc(), g_gateway_config, http_requests_in_flight, and http_requests_total.
Referenced by on_message_complete().
metrics_server_start()
void metrics_server_start (void)
启动指标服务器
在独立线程中启动 Prometheus 指标抓取服务器。
Definition at line 399 of file metrics.c.
References g_gateway_config, and metrics_server_thread().
Referenced by main().
metrics_upstream_duration()
void metrics_upstream_duration (double duration_sec)
记录上游服务延迟
记录向后端服务发起请求的延迟。
Parameters
duration_sec 上游服务响应时间（秒）
Definition at line 189 of file metrics.c.
References g_gateway_config, histogram_observe(), and http_upstream_duration_seconds.
Referenced by forward_to_service().
on_new_connection()
void on_new_connection (uv_stream_t * server, int status)
新连接回调函数
当服务器接受新客户端连接时调用此函数。 初始化客户端上下文、HTTP 解析器，并开始读取数据。
Parameters
server 服务器 TCP 句柄
status 状态码 (0 表示成功)
Definition at line 148 of file network.c.
References alloc_buffer(), get_time_nanoseconds(), client_ctx_t::handle, client_ctx_t::is_sampled, on_body(), on_message_complete(), on_read(), on_url(), client_ctx_t::parser, client_ctx_t::request_id, client_ctx_t::request_start_time, client_ctx_t::settings, client_ctx_t::span_id, client_ctx_t::trace_id, and tracing_init_context().
Referenced by worker_thread().
on_write_completed()
void on_write_completed (uv_write_t * req, int status)
写入完成回调函数
当响应数据写入完成后调用此函数。 负责清理写入上下文，并根据 Keep-Alive 设置决定是否关闭连接。
Parameters
req 写入请求句柄
status 状态码
Definition at line 110 of file network.c.
References write_ctx_t::body_ptr, g_gateway_config, get_time_nanoseconds(), client_ctx_t::handle, write_ctx_t::header_ptr, log_info(), metrics_request_end(), on_client_close(), client_ctx_t::request_start_time, and tracing_export_span().
Referenced by send_response().
parse_ip_address()
int parse_ip_address (const char * host, ip_address_t * addr)
解析 IP 地址
将主机名或 IP 地址字符串解析为 ip_address_t 结构。 支持 IPv4、IPv6 和域名。
Parameters
host 主机名字符串
addr 输出参数，解析结果
Returns
int 0 表示成功，-1 表示失败
Definition at line 14 of file service_registry.c.
References ip_address_t::address, ip_address_t::is_domain, and ip_address_t::is_ipv6.
Referenced by service_register_with_ipv6().
pool_alloc()
void * pool_alloc (client_ctx_t * ctx, size_t size)
从内存池分配内存
从连接的内存池中分配指定大小的内存。 如果池空间不足，回退到 malloc。
Parameters
ctx 客户端上下文
size 需要的字节数
Returns
void* 分配的内存指针
Definition at line 5 of file utils.c.
References mem_pool_t::data, client_ctx_t::pool, POOL_SIZE, and mem_pool_t::used.
Referenced by get_query_param().
route_request()
void route_request (client_ctx_t * client)
路由请求处理函数
根据请求 URL 和方法进行路由匹配，分发到对应的处理函数。 支持内置端点和后端服务代理。
Parameters
client 客户端上下文
Definition at line 10 of file router.c.
References forward_to_service(), handle_get_services(), handle_service_register(), handle_service_unregister(), service_t::name, client_ctx_t::parser, send_response(), service_find_by_path(), service_select_instance(), and client_ctx_t::url.
Referenced by on_message_complete().
send_response()
void send_response (client_ctx_t * client, int status_code, const char * content_type, char * body_to_send)
发送 HTTP 响应
构造并发送完整的 HTTP 响应报文。 使用异步写入，在写入完成回调中清理资源。
Parameters
client 客户端上下文
status_code HTTP 状态码
content_type Content-Type 头部值
body_to_send 响应体（堆内存，由回调释放）
Definition at line 89 of file router.c.
References write_ctx_t::body_ptr, write_ctx_t::bufs, client_ctx_t::handle, write_ctx_t::header_ptr, on_write_completed(), and write_ctx_t::req.
Referenced by forward_to_service(), handle_get_employees(), handle_get_services(), handle_service_register(), handle_service_unregister(), proxy_complete_callback(), and route_request().
service_deregister()
int service_deregister (const char * name, const char * host, int port)
注销服务
从注册表中移除指定的服务实例。
Parameters
name 服务名称
host 服务主机地址
port 服务端口
Returns
int 0 表示成功，-1 表示未找到
Definition at line 170 of file service_registry.c.
References g_registry, service_instance_t::host, service_t::instance_count, service_t::instances, service_t::lock, service_t::name, and service_instance_t::port.
Referenced by handle_service_unregister().
service_find_by_path()
service_t * service_find_by_path (const char * path)
根据路径查找服务
根据请求路径匹配对应的后端服务。
Parameters
path 请求路径
Returns
service_t* 匹配的服务指针，未找到返回 NULL
Definition at line 205 of file service_registry.c.
References g_registry, and service_t::path_prefix.
Referenced by route_request().
service_register()
int service_register (const char * name, const char * path_prefix, const char * host, int port, protocol_t protocol, const char * health_endpoint, int verify_ssl)
注册服务（简化版）
向注册表中注册一个服务实例。
Parameters
name 服务名称
path_prefix 路由路径前缀
host 服务主机地址
port 服务端口
protocol 协议类型
health_endpoint 健康检查端点
verify_ssl 是否验证 SSL
Returns
int 0 表示成功，-1 表示失败
Definition at line 77 of file service_registry.c.
References service_register_with_ipv6().
service_register_with_ipv6()
int service_register_with_ipv6 (const char * name, const char * description, const char * path_prefix, const char * host, int port, protocol_t protocol, const char * health_endpoint, int verify_ssl, int is_ipv6)
注册服务（完整版，支持 IPv6）
向注册表中注册一个服务实例，支持 IPv6 地址。
Parameters
name 服务名称
description 服务描述
path_prefix 路由路径前缀
host 服务主机地址
port 服务端口
protocol 协议类型
health_endpoint 健康检查端点
verify_ssl 是否验证 SSL
is_ipv6 是否 IPv6 地址
Returns
int 0 表示成功，-1 表示失败
Definition at line 85 of file service_registry.c.
References service_instance_t::ca_cert_path, service_t::description, service_instance_t::endpoint, g_registry, service_instance_t::health, service_t::health_endpoint, service_instance_t::host, service_t::instance_count, service_t::instances, service_instance_t::ip_addr, service_instance_t::last_check_time, service_t::lock, MAX_SERVICE_INSTANCES, MAX_SERVICES, service_t::name, parse_ip_address(), service_t::path_prefix, service_instance_t::port, service_instance_t::protocol, PROTOCOL_HTTPS, service_instance_t::request_count, SERVICE_HOST_LEN, SERVICE_NAME_LEN, SERVICE_UNKNOWN, and service_instance_t::verify_ssl.
Referenced by handle_service_register(), load_service_config(), and service_register().
service_registry_init()
void service_registry_init (void)
初始化服务注册表
初始化全局服务注册表，包括互斥锁等。
Definition at line 5 of file service_registry.c.
References g_registry.
Referenced by main().
service_select_instance()
service_instance_t * service_select_instance (service_t * service)
选择服务实例（负载均衡）
使用 Round-Robin 算法从服务实例中选择一个。
Parameters
service 服务指针
Returns
service_instance_t* 选中的实例指针
Definition at line 225 of file service_registry.c.
References service_t::current_instance, service_instance_t::health, service_instance_t::host, service_t::instance_count, service_t::instances, service_instance_t::ip_addr, ip_address_t::is_ipv6, service_t::lock, service_t::name, service_instance_t::port, service_instance_t::protocol, PROTOCOL_HTTPS, service_instance_t::request_count, and SERVICE_UNHEALTHY.
Referenced by route_request().
start_health_checker()
void start_health_checker (void)
启动健康检查器
在独立线程中启动定时健康检查任务。
Definition at line 170 of file health_checker.c.
References g_gateway_config, health_check_callback(), health_loop, and health_timer.
Referenced by health_check_thread().
tracing_add_event()
void tracing_add_event (client_ctx_t * ctx, const char * event_name, const char * attributes)
添加追踪事件
在当前跨度中添加事件标记。
Parameters
ctx 客户端上下文
event_name 事件名称
attributes 事件属性（JSON 格式）
Definition at line 189 of file tracer.c.
References g_gateway_config, client_ctx_t::is_sampled, and log_debug().
tracing_export_span()
void tracing_export_span (client_ctx_t * ctx, const char * operation, double duration_ms)
导出追踪跨度
在请求完成时导出追踪数据到 Jaeger/Zipkin 等后端。
Parameters
ctx 客户端上下文
operation 操作名称
duration_ms 操作持续时间（毫秒）
Definition at line 154 of file tracer.c.
References export_to_console(), export_to_http_collector(), g_gateway_config, client_ctx_t::is_sampled, client_ctx_t::span_id, and client_ctx_t::trace_id.
Referenced by on_write_completed().
tracing_get_outgoing_traceparent()
void tracing_get_outgoing_traceparent (client_ctx_t * ctx, char * buffer, size_t size)
获取传出追踪上下文
生成用于向后端服务发起请求的 traceparent。
Parameters
ctx 客户端上下文
buffer 输出缓冲区
size 缓冲区大小
Definition at line 174 of file tracer.c.
References build_traceparent_header(), g_gateway_config, generate_span_id(), client_ctx_t::is_sampled, and client_ctx_t::trace_id.
Referenced by forward_to_service().
tracing_init_context()
void tracing_init_context (client_ctx_t * ctx, const char * incoming_traceparent)
初始化追踪上下文
从请求头解析 traceparent，或生成新的追踪 ID。
Parameters
ctx 客户端上下文
incoming_traceparent 传入的 traceparent 字符串
Definition at line 92 of file tracer.c.
References g_gateway_config, generate_random_hex(), generate_span_id(), generate_trace_id(), client_ctx_t::is_sampled, log_debug(), parse_traceparent(), client_ctx_t::request_id, should_sample(), client_ctx_t::span_id, and client_ctx_t::trace_id.
Referenced by on_new_connection().
Variable Documentation
g_gateway_config
gateway_config_t g_gateway_config
Definition at line 275 of file gateway.h.
Referenced by export_to_http_collector(), forward_to_service(), init_tcp_server_ipv6(), load_gateway_config(), log_request(), main(), metrics_init(), metrics_request_end(), metrics_request_start(), metrics_server_start(), metrics_server_thread(), metrics_upstream_duration(), on_client_close(), on_message_complete(), on_write_completed(), should_sample(), start_health_checker(), tracing_add_event(), tracing_export_span(), tracing_get_outgoing_traceparent(), tracing_init_context(), and worker_thread().
g_registry
service_registry_t g_registry extern
Definition at line 3 of file service_registry.c.
Referenced by handle_get_services(), health_check_callback(), service_deregister(), service_find_by_path(), service_register_with_ipv6(), and service_registry_init().