微服务网关: src/health_checker.c File Reference
health_checker.c File Reference
#include "gateway.h"
Macros
#define MAX_FAILURE_COUNT 3
Functions
size_t health_write_callback (void *contents, size_t size, size_t nmemb, void *userp)
static void remove_unhealthy_service (service_t *svc, int instance_index)
static void remove_service_from_registry (service_registry_t *registry, int service_index)
void check_service_health (service_instance_t *instance)
void health_check_callback (uv_timer_t *handle)
void start_health_checker ()
启动健康检查器
Variables
static uv_timer_t health_timer
static uv_loop_t * health_loop
Macro Definition Documentation
MAX_FAILURE_COUNT
#define MAX_FAILURE_COUNT 3
Definition at line 5 of file health_checker.c.
Referenced by check_service_health(), health_check_callback(), and remove_unhealthy_service().
Function Documentation
check_service_health()
void check_service_health (service_instance_t * instance)
Definition at line 56 of file health_checker.c.
References service_instance_t::ca_cert_path, service_instance_t::endpoint, service_instance_t::failure_count, service_instance_t::health, health_loop, health_write_callback(), service_instance_t::host, service_instance_t::ip_addr, ip_address_t::is_ipv6, service_instance_t::last_check_time, MAX_FAILURE_COUNT, service_instance_t::port, service_instance_t::protocol, PROTOCOL_HTTPS, SERVICE_HEALTHY, SERVICE_UNHEALTHY, and service_instance_t::verify_ssl.
Referenced by health_check_callback().
health_check_callback()
void health_check_callback (uv_timer_t * handle)
Definition at line 133 of file health_checker.c.
References check_service_health(), service_instance_t::failure_count, g_registry, service_t::instance_count, service_t::instances, service_t::lock, MAX_FAILURE_COUNT, remove_service_from_registry(), and remove_unhealthy_service().
Referenced by start_health_checker().
health_write_callback()
size_t health_write_callback (void * contents, size_t size, size_t nmemb, void * userp)
Definition at line 7 of file health_checker.c.
Referenced by check_service_health().
remove_service_from_registry()
void remove_service_from_registry (service_registry_t * registry, int service_index) static
Definition at line 40 of file health_checker.c.
References service_t::name, service_registry_t::service_count, and service_registry_t::services.
Referenced by health_check_callback().
remove_unhealthy_service()
void remove_unhealthy_service (service_t * svc, int instance_index) static
Definition at line 16 of file health_checker.c.
References service_t::current_instance, service_instance_t::host, service_t::instance_count, service_t::instances, MAX_FAILURE_COUNT, service_t::name, and service_instance_t::port.
Referenced by health_check_callback().
start_health_checker()
void start_health_checker (void)
启动健康检查器
在独立线程中启动定时健康检查任务。
Definition at line 170 of file health_checker.c.
References g_gateway_config, health_check_callback(), health_loop, and health_timer.
Referenced by health_check_thread().
Variable Documentation
health_loop
uv_loop_t* health_loop static
Definition at line 4 of file health_checker.c.
Referenced by check_service_health(), and start_health_checker().
health_timer
uv_timer_t health_timer static
Definition at line 3 of file health_checker.c.
Referenced by start_health_checker().