微服务网关: src/logger.c File Reference
logger.c File Reference
#include "gateway.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <sys/time.h>
Functions
static void get_timestamp_iso (char *buffer, size_t size)
结构化日志模块 支持 JSON 格式输出，高性能，线程安全
uint64_t get_time_nanoseconds (void)
获取纳秒级时间戳
static const char * log_level_str (log_level_t level)
static void escape_json_string (const char *input, char *output, size_t output_size)
void log_request (log_level_t level, client_ctx_t *ctx, const char *event, const char *format,...)
记录请求日志（通用接口）
void log_debug (client_ctx_t *ctx, const char *event, const char *format,...)
记录调试日志
void log_info (client_ctx_t *ctx, const char *event, const char *format,...)
记录信息日志
void log_warn (client_ctx_t *ctx, const char *event, const char *format,...)
记录警告日志
void log_error (client_ctx_t *ctx, const char *event, const char *format,...)
记录错误日志
Function Documentation
escape_json_string()
void escape_json_string (const char * input, char * output, size_t output_size) static
Definition at line 59 of file logger.c.
Referenced by log_request().
get_time_nanoseconds()
uint64_t get_time_nanoseconds (void)
获取纳秒级时间戳
Returns
uint64_t 纳秒级时间戳（相对于系统启动时间）
Definition at line 33 of file logger.c.
Referenced by forward_to_service(), on_new_connection(), and on_write_completed().
get_timestamp_iso()
void get_timestamp_iso (char * buffer, size_t size) static
结构化日志模块 支持 JSON 格式输出，高性能，线程安全
Definition at line 14 of file logger.c.
Referenced by log_request().
log_debug()
void log_debug (client_ctx_t * ctx, const char * event, const char * format, ...)
记录调试日志
Parameters
ctx 客户端上下文
event 事件名称
format 格式化字符串
Definition at line 204 of file logger.c.
References LOG_LEVEL_DEBUG, and log_request().
Referenced by export_to_http_collector(), forward_to_service(), on_client_close(), tracing_add_event(), and tracing_init_context().
log_error()
void log_error (client_ctx_t * ctx, const char * event, const char * format, ...)
记录错误日志
Parameters
ctx 客户端上下文
event 事件名称
format 格式化字符串
Definition at line 234 of file logger.c.
References LOG_LEVEL_ERROR, and log_request().
Referenced by forward_to_service().
log_info()
void log_info (client_ctx_t * ctx, const char * event, const char * format, ...)
记录信息日志
Parameters
ctx 客户端上下文
event 事件名称
format 格式化字符串
Definition at line 214 of file logger.c.
References LOG_LEVEL_INFO, and log_request().
Referenced by forward_to_service(), main(), metrics_init(), on_message_complete(), and on_write_completed().
log_level_str()
const char * log_level_str (log_level_t level) static
Definition at line 41 of file logger.c.
References LOG_LEVEL_DEBUG, LOG_LEVEL_ERROR, LOG_LEVEL_INFO, and LOG_LEVEL_WARN.
Referenced by load_gateway_config(), and log_request().
log_request()
void log_request (log_level_t level, client_ctx_t * ctx, const char * event, const char * format, ...)
记录请求日志（通用接口）
根据配置的日志级别和格式，记录请求相关的日志。 支持 JSON 和文本两种格式。
Parameters
level 日志级别
ctx 客户端上下文
event 事件名称
format 格式化字符串
Definition at line 106 of file logger.c.
References escape_json_string(), g_gateway_config, get_timestamp_iso(), log_level_str(), client_ctx_t::request_id, client_ctx_t::span_id, and client_ctx_t::trace_id.
Referenced by log_debug(), log_error(), log_info(), and log_warn().
log_warn()
void log_warn (client_ctx_t * ctx, const char * event, const char * format, ...)
记录警告日志
Parameters
ctx 客户端上下文
event 事件名称
format 格式化字符串
Definition at line 224 of file logger.c.
References LOG_LEVEL_WARN, and log_request().