微服务网关: src/metrics.c File Reference
metrics.c File Reference
#include "gateway.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <pthread.h>
#include <uv.h>
#include <inttypes.h>
#include <stddef.h>
Data Structures
struct metric_counter_t
struct histogram_bucket_t
struct metric_histogram_t
struct metrics_client_t
Macros
#define APPEND(fmt, ...)
Enumerations
enum metric_type_t { METRIC_COUNTER , METRIC_GAUGE , METRIC_HISTOGRAM }
Prometheus 指标收集模块 高性能、线程安全的指标收集
Functions
static void init_metrics (void)
static void counter_inc (metric_counter_t *counter)
static void counter_dec (metric_counter_t *counter)
static void histogram_observe (metric_histogram_t *hist, double value)
void metrics_init (void)
初始化指标系统
void metrics_request_start (client_ctx_t *ctx)
记录请求开始
void metrics_request_end (client_ctx_t *ctx, int status_code, double duration_sec)
记录请求完成
void metrics_upstream_duration (double duration_sec)
记录上游服务延迟
void metrics_generate_output (char *buffer, size_t buffer_size)
生成 Prometheus 格式输出
static void metrics_on_close (uv_handle_t *handle)
static void metrics_on_write_complete (uv_write_t *req, int status)
static void metrics_alloc_buffer (uv_handle_t *handle, size_t suggested_size, uv_buf_t *buf)
static void metrics_read_cb (uv_stream_t *client, ssize_t nread, const uv_buf_t *buf)
static void metrics_new_connection (uv_stream_t *server, int status)
static void * metrics_server_thread (void *arg)
void metrics_server_start (void)
启动指标服务器
Variables
static metric_counter_t http_requests_total
static metric_counter_t http_request_errors_total
static histogram_bucket_t request_duration_buckets []
static metric_histogram_t http_request_duration_seconds
static metric_histogram_t http_upstream_duration_seconds
static metric_counter_t http_requests_in_flight
static uv_tcp_t metrics_server
static uv_loop_t * metrics_loop = NULL
Macro Definition Documentation
APPEND
#define APPEND (fmt, ...)
Value:
        do { \
        int n = snprintf(buffer + offset, buffer_size - offset, fmt, ##__VA_ARGS__); \
        if (n > 0 && (size_t)n < buffer_size - offset) { \
            offset += n; \
        } \
    } while(0)
Referenced by metrics_generate_output().
Enumeration Type Documentation
metric_type_t
enum metric_type_t
Prometheus 指标收集模块 高性能、线程安全的指标收集
Enumerator
METRIC_COUNTER
METRIC_GAUGE
METRIC_HISTOGRAM
Definition at line 18 of file metrics.c.
Function Documentation
counter_dec()
void counter_dec (metric_counter_t * counter) static
Definition at line 121 of file metrics.c.
References metric_counter_t::lock, and metric_counter_t::value.
Referenced by metrics_request_end().
counter_inc()
void counter_inc (metric_counter_t * counter) static
Definition at line 113 of file metrics.c.
References metric_counter_t::lock, and metric_counter_t::value.
Referenced by metrics_request_end(), and metrics_request_start().
histogram_observe()
void histogram_observe (metric_histogram_t * hist, double value) static
Definition at line 129 of file metrics.c.
References metric_histogram_t::bucket_count, metric_histogram_t::buckets, histogram_bucket_t::count, histogram_bucket_t::le, metric_histogram_t::lock, metric_histogram_t::sum, and metric_histogram_t::total_count.
Referenced by metrics_request_end(), and metrics_upstream_duration().
init_metrics()
void init_metrics (void) static
Definition at line 101 of file metrics.c.
References http_request_duration_seconds, http_request_errors_total, http_requests_in_flight, http_requests_total, and http_upstream_duration_seconds.
Referenced by metrics_init().
metrics_alloc_buffer()
void metrics_alloc_buffer (uv_handle_t * handle, size_t suggested_size, uv_buf_t * buf) static
Definition at line 315 of file metrics.c.
Referenced by metrics_new_connection().
metrics_generate_output()
void metrics_generate_output (char * buffer, size_t buffer_size)
生成 Prometheus 格式输出
将所有指标格式化为 Prometheus 文本格式。
Parameters
buffer 输出缓冲区
buffer_size 缓冲区大小
Definition at line 199 of file metrics.c.
References APPEND, http_request_duration_seconds, http_request_errors_total, http_requests_in_flight, http_requests_total, and http_upstream_duration_seconds.
Referenced by metrics_read_cb().
metrics_init()
void metrics_init (void)
初始化指标系统
初始化所有 Prometheus 指标的初始值。
Definition at line 150 of file metrics.c.
References g_gateway_config, init_metrics(), and log_info().
Referenced by main().
metrics_new_connection()
void metrics_new_connection (uv_stream_t * server, int status) static
Definition at line 360 of file metrics.c.
References metrics_client_t::client, metrics_alloc_buffer(), metrics_loop, and metrics_read_cb().
Referenced by metrics_server_thread().
metrics_on_close()
void metrics_on_close (uv_handle_t * handle) static
Definition at line 284 of file metrics.c.
References metrics_client_t::response_data.
Referenced by metrics_on_write_complete(), and metrics_read_cb().
metrics_on_write_complete()
void metrics_on_write_complete (uv_write_t * req, int status) static
Definition at line 298 of file metrics.c.
References metrics_client_t::client, and metrics_on_close().
Referenced by metrics_read_cb().
metrics_read_cb()
void metrics_read_cb (uv_stream_t * client, ssize_t nread, const uv_buf_t * buf) static
Definition at line 322 of file metrics.c.
References metrics_client_t::client, metrics_generate_output(), metrics_on_close(), metrics_on_write_complete(), metrics_client_t::response_data, and metrics_client_t::write_req.
Referenced by metrics_new_connection().
metrics_request_end()
void metrics_request_end (client_ctx_t * ctx, int status_code, double duration_sec)
记录请求完成
在请求完成时调用，更新请求总数、延迟直方图等指标。
Parameters
ctx 客户端上下文
status_code HTTP 状态码
duration_sec 请求持续时间（秒）
Definition at line 171 of file metrics.c.
References counter_dec(), counter_inc(), g_gateway_config, histogram_observe(), http_request_duration_seconds, http_request_errors_total, and http_requests_in_flight.
Referenced by on_write_completed().
metrics_request_start()
void metrics_request_start (client_ctx_t * ctx)
记录请求开始
在请求开始时调用，记录开始时间和初始状态。
Parameters
ctx 客户端上下文
Definition at line 160 of file metrics.c.
References counter_inc(), g_gateway_config, http_requests_in_flight, and http_requests_total.
Referenced by on_message_complete().
metrics_server_start()
void metrics_server_start (void)
启动指标服务器
在独立线程中启动 Prometheus 指标抓取服务器。
Definition at line 399 of file metrics.c.
References g_gateway_config, and metrics_server_thread().
Referenced by main().
metrics_server_thread()
void * metrics_server_thread (void * arg) static
Definition at line 375 of file metrics.c.
References g_gateway_config, metrics_loop, metrics_new_connection(), and metrics_server.
Referenced by metrics_server_start().
metrics_upstream_duration()
void metrics_upstream_duration (double duration_sec)
记录上游服务延迟
记录向后端服务发起请求的延迟。
Parameters
duration_sec 上游服务响应时间（秒）
Definition at line 189 of file metrics.c.
References g_gateway_config, histogram_observe(), and http_upstream_duration_seconds.
Referenced by forward_to_service().
Variable Documentation
http_request_duration_seconds
metric_histogram_t http_request_duration_seconds static
Initial value:
= {
    .name = "gateway_http_request_duration_seconds",
    .help = "HTTP request latency in seconds",
    .buckets = request_duration_buckets,
    .bucket_count = sizeof(request_duration_buckets) / sizeof(request_duration_buckets[0])
}
Definition at line 79 of file metrics.c.
Referenced by init_metrics(), metrics_generate_output(), and metrics_request_end().
http_request_errors_total
metric_counter_t http_request_errors_total static
Initial value:
= {
    .name = "gateway_http_request_errors_total",
    .help = "Total number of failed HTTP requests"
}
Definition at line 57 of file metrics.c.
Referenced by init_metrics(), metrics_generate_output(), and metrics_request_end().
http_requests_in_flight
metric_counter_t http_requests_in_flight static
Initial value:
= {
    .name = "gateway_http_requests_in_flight",
    .help = "Current number of requests being processed"
}
Definition at line 95 of file metrics.c.
Referenced by init_metrics(), metrics_generate_output(), metrics_request_end(), and metrics_request_start().
http_requests_total
metric_counter_t http_requests_total static
Initial value:
= {
    .name = "gateway_http_requests_total",
    .help = "Total number of HTTP requests"
}
Definition at line 52 of file metrics.c.
Referenced by init_metrics(), metrics_generate_output(), and metrics_request_start().
http_upstream_duration_seconds
metric_histogram_t http_upstream_duration_seconds static
Initial value:
= {
    .name = "gateway_http_upstream_duration_seconds",
    .help = "Upstream service latency in seconds",
    .buckets = request_duration_buckets,
    .bucket_count = sizeof(request_duration_buckets) / sizeof(request_duration_buckets[0])
}
Definition at line 87 of file metrics.c.
Referenced by init_metrics(), metrics_generate_output(), and metrics_upstream_duration().
metrics_loop
uv_loop_t* metrics_loop = NULL static
Definition at line 276 of file metrics.c.
Referenced by metrics_new_connection(), and metrics_server_thread().
metrics_server
uv_tcp_t metrics_server static
Definition at line 275 of file metrics.c.
Referenced by metrics_server_thread().
request_duration_buckets
histogram_bucket_t request_duration_buckets[] static
Initial value:
= {
    {0.001, 0},
    {0.005, 0},
    {0.010, 0},
    {0.025, 0},
    {0.050, 0},
    {0.100, 0},
    {0.250, 0},
    {0.500, 0},
    {1.000, 0},
    {2.500, 0},
    {5.000, 0},
    {10.000, 0},
    {-1, 0}
}
Definition at line 63 of file metrics.c.