微服务网关: src/network.c File Reference
network.c File Reference
#include "gateway.h"
Functions
void alloc_buffer (uv_handle_t *handle, size_t suggested, uv_buf_t *buf)
void on_close (uv_handle_t *handle)
static void on_client_close (uv_handle_t *handle)
int on_body (llhttp_t *parser, const char *at, size_t length)
int on_url (llhttp_t *parser, const char *at, size_t length)
int on_message_complete (llhttp_t *parser)
void on_read (uv_stream_t *client_stream, ssize_t nread, const uv_buf_t *buf)
void on_write_completed (uv_write_t *req, int status)
写入完成回调函数
void on_new_connection (uv_stream_t *server, int status)
新连接回调函数
Function Documentation
alloc_buffer()
void alloc_buffer (uv_handle_t * handle, size_t suggested, uv_buf_t * buf)
Definition at line 4 of file network.c.
Referenced by on_new_connection().
on_body()
int on_body (llhttp_t * parser, const char * at, size_t length)
Definition at line 38 of file network.c.
References client_ctx_t::body_buffer, and client_ctx_t::body_len.
Referenced by on_new_connection().
on_client_close()
void on_client_close (uv_handle_t * handle) static
Definition at line 19 of file network.c.
References client_ctx_t::body_buffer, g_gateway_config, and log_debug().
Referenced by on_write_completed().
on_close()
void on_close (uv_handle_t * handle)
Definition at line 11 of file network.c.
References client_ctx_t::body_buffer.
Referenced by on_read().
on_message_complete()
int on_message_complete (llhttp_t * parser)
Definition at line 67 of file network.c.
References client_ctx_t::body_buffer, client_ctx_t::body_len, g_gateway_config, log_info(), metrics_request_start(), client_ctx_t::parser, client_ctx_t::pool, route_request(), client_ctx_t::url, and mem_pool_t::used.
Referenced by on_new_connection().
on_new_connection()
void on_new_connection (uv_stream_t * server, int status)
新连接回调函数
当服务器接受新客户端连接时调用此函数。 初始化客户端上下文、HTTP 解析器，并开始读取数据。
Parameters
server 服务器 TCP 句柄
status 状态码 (0 表示成功)
Definition at line 148 of file network.c.
References alloc_buffer(), get_time_nanoseconds(), client_ctx_t::handle, client_ctx_t::is_sampled, on_body(), on_message_complete(), on_read(), on_url(), client_ctx_t::parser, client_ctx_t::request_id, client_ctx_t::request_start_time, client_ctx_t::settings, client_ctx_t::span_id, client_ctx_t::trace_id, and tracing_init_context().
Referenced by worker_thread().
on_read()
void on_read (uv_stream_t * client_stream, ssize_t nread, const uv_buf_t * buf)
Definition at line 96 of file network.c.
References on_close(), and client_ctx_t::parser.
Referenced by on_new_connection().
on_url()
int on_url (llhttp_t * parser, const char * at, size_t length)
Definition at line 49 of file network.c.
References client_ctx_t::url.
Referenced by on_new_connection().
on_write_completed()
void on_write_completed (uv_write_t * req, int status)
写入完成回调函数
当响应数据写入完成后调用此函数。 负责清理写入上下文，并根据 Keep-Alive 设置决定是否关闭连接。
Parameters
req 写入请求句柄
status 状态码
Definition at line 110 of file network.c.
References write_ctx_t::body_ptr, g_gateway_config, get_time_nanoseconds(), client_ctx_t::handle, write_ctx_t::header_ptr, log_info(), metrics_request_end(), on_client_close(), client_ctx_t::request_start_time, and tracing_export_span().
Referenced by send_response().