微服务网关: src/proxy.c File Reference
proxy.c File Reference
#include "gateway.h"
Functions
size_t proxy_write_callback (void *contents, size_t size, size_t nmemb, void *userp)
void proxy_complete_callback (uv_async_t *async)
void forward_to_service (client_ctx_t *client, service_instance_t *instance)
转发请求到后端服务
Function Documentation
forward_to_service()
void forward_to_service (client_ctx_t * client, service_instance_t * instance)
转发请求到后端服务
将客户端请求异步转发到选中的后端服务实例。
Parameters
client 客户端上下文
instance 目标服务实例
Definition at line 55 of file proxy.c.
References client_ctx_t::body_buffer, client_ctx_t::body_len, service_instance_t::ca_cert_path, proxy_request_t::client, proxy_request_t::curl, g_gateway_config, get_time_nanoseconds(), client_ctx_t::handle, proxy_request_t::headers, service_instance_t::health, service_instance_t::host, service_instance_t::ip_addr, ip_address_t::is_ipv6, client_ctx_t::is_sampled, log_debug(), log_error(), log_info(), metrics_upstream_duration(), client_ctx_t::parser, service_instance_t::port, service_instance_t::protocol, PROTOCOL_HTTPS, proxy_complete_callback(), proxy_write_callback(), proxy_request_t::response_data, send_response(), SERVICE_UNHEALTHY, proxy_request_t::status_code, tracing_get_outgoing_traceparent(), client_ctx_t::url, and service_instance_t::verify_ssl.
Referenced by route_request().
proxy_complete_callback()
void proxy_complete_callback (uv_async_t * async)
Definition at line 18 of file proxy.c.
References proxy_request_t::client, proxy_request_t::curl, proxy_request_t::headers, proxy_request_t::response_data, proxy_request_t::response_size, send_response(), and proxy_request_t::status_code.
Referenced by forward_to_service().
proxy_write_callback()
size_t proxy_write_callback (void * contents, size_t size, size_t nmemb, void * userp)
Definition at line 3 of file proxy.c.
References proxy_request_t::response_data, and proxy_request_t::response_size.
Referenced by forward_to_service().