微服务网关: src/router.c File Reference
router.c File Reference
#include "gateway.h"
Functions
void route_request (client_ctx_t *client)
路由请求处理函数
void send_response (client_ctx_t *client, int status_code, const char *content_type, char *body_to_send)
发送 HTTP 响应
void handle_get_services (client_ctx_t *client)
获取已注册服务列表
void handle_service_register (client_ctx_t *client)
处理服务注册请求 POST /api/services/register
void handle_service_unregister (client_ctx_t *client)
处理服务注销请求 DELETE /api/services/unregister
void handle_get_employees (client_ctx_t *client)
具体业务处理：查询雇员 支持路径：/api/employees (全表) 或 /api/employees?id=1001 (单条)
Variables
static employee_t employee_db []
static int db_count = 3
Function Documentation
handle_get_employees()
void handle_get_employees (client_ctx_t * client)
具体业务处理：查询雇员 支持路径：/api/employees (全表) 或 /api/employees?id=1001 (单条)
获取员工列表处理器
Definition at line 324 of file router.c.
References db_count, employee_t::dept, employee_db, get_query_param(), employee_t::id, employee_t::name, employee_t::salary, and send_response().
handle_get_services()
void handle_get_services (client_ctx_t * client)
获取已注册服务列表
获取服务列表处理器
Definition at line 137 of file router.c.
References service_t::description, g_registry, service_instance_t::health, service_t::health_endpoint, service_instance_t::host, service_t::instance_count, service_t::instances, service_instance_t::ip_addr, ip_address_t::is_ipv6, service_t::lock, service_t::name, service_t::path_prefix, service_instance_t::port, service_instance_t::protocol, PROTOCOL_HTTPS, service_instance_t::request_count, send_response(), SERVICE_HEALTHY, SERVICE_UNHEALTHY, and service_instance_t::verify_ssl.
Referenced by route_request().
handle_service_register()
void handle_service_register (client_ctx_t * client)
处理服务注册请求 POST /api/services/register
服务注册处理器
Definition at line 197 of file router.c.
References client_ctx_t::body_buffer, PROTOCOL_HTTP, PROTOCOL_HTTPS, send_response(), and service_register_with_ipv6().
Referenced by route_request().
handle_service_unregister()
void handle_service_unregister (client_ctx_t * client)
处理服务注销请求 DELETE /api/services/unregister
服务注销处理器
Definition at line 273 of file router.c.
References client_ctx_t::body_buffer, send_response(), and service_deregister().
Referenced by route_request().
route_request()
void route_request (client_ctx_t * client)
路由请求处理函数
根据请求 URL 和方法进行路由匹配，分发到对应的处理函数。 支持内置端点和后端服务代理。
Parameters
client 客户端上下文
Definition at line 10 of file router.c.
References forward_to_service(), handle_get_services(), handle_service_register(), handle_service_unregister(), service_t::name, client_ctx_t::parser, send_response(), service_find_by_path(), service_select_instance(), and client_ctx_t::url.
Referenced by on_message_complete().
send_response()
void send_response (client_ctx_t * client, int status_code, const char * content_type, char * body_to_send)
发送 HTTP 响应
构造并发送完整的 HTTP 响应报文。 使用异步写入，在写入完成回调中清理资源。
Parameters
client 客户端上下文
status_code HTTP 状态码
content_type Content-Type 头部值
body_to_send 响应体（堆内存，由回调释放）
Definition at line 89 of file router.c.
References write_ctx_t::body_ptr, write_ctx_t::bufs, client_ctx_t::handle, write_ctx_t::header_ptr, on_write_completed(), and write_ctx_t::req.
Referenced by forward_to_service(), handle_get_employees(), handle_get_services(), handle_service_register(), handle_service_unregister(), proxy_complete_callback(), and route_request().
Variable Documentation
db_count
int db_count = 3 static
Definition at line 8 of file router.c.
Referenced by handle_get_employees().
employee_db
employee_t employee_db[] static
Initial value:
= {
    {1001, "张三", "技术部", 15000.5},
    {1002, "李四", "市场部", 12000.0},
    {1003, "王五", "研发部", 18000.7}}
Definition at line 4 of file router.c.
Referenced by handle_get_employees().