微服务网关: src/service_registry.c File Reference
service_registry.c File Reference
#include "gateway.h"
Functions
void service_registry_init ()
初始化服务注册表
int parse_ip_address (const char *host, ip_address_t *addr)
解析 IP 地址
int service_register (const char *name, const char *path_prefix, const char *host, int port, protocol_t protocol, const char *health_endpoint, int verify_ssl)
注册服务（简化版）
int service_register_with_ipv6 (const char *name, const char *description, const char *path_prefix, const char *host, int port, protocol_t protocol, const char *health_endpoint, int verify_ssl, int is_ipv6)
注册服务（完整版，支持 IPv6）
int service_deregister (const char *name, const char *host, int port)
注销服务
service_t * service_find_by_path (const char *path)
根据路径查找服务
service_instance_t * service_select_instance (service_t *service)
选择服务实例（负载均衡）
Variables
service_registry_t g_registry
Function Documentation
parse_ip_address()
int parse_ip_address (const char * host, ip_address_t * addr)
解析 IP 地址
将主机名或 IP 地址字符串解析为 ip_address_t 结构。 支持 IPv4、IPv6 和域名。
Parameters
host 主机名字符串
addr 输出参数，解析结果
Returns
int 0 表示成功，-1 表示失败
Definition at line 14 of file service_registry.c.
References ip_address_t::address, ip_address_t::is_domain, and ip_address_t::is_ipv6.
Referenced by service_register_with_ipv6().
service_deregister()
int service_deregister (const char * name, const char * host, int port)
注销服务
从注册表中移除指定的服务实例。
Parameters
name 服务名称
host 服务主机地址
port 服务端口
Returns
int 0 表示成功，-1 表示未找到
Definition at line 170 of file service_registry.c.
References g_registry, service_instance_t::host, service_t::instance_count, service_t::instances, service_t::lock, service_t::name, and service_instance_t::port.
Referenced by handle_service_unregister().
service_find_by_path()
service_t * service_find_by_path (const char * path)
根据路径查找服务
根据请求路径匹配对应的后端服务。
Parameters
path 请求路径
Returns
service_t* 匹配的服务指针，未找到返回 NULL
Definition at line 205 of file service_registry.c.
References g_registry, and service_t::path_prefix.
Referenced by route_request().
service_register()
int service_register (const char * name, const char * path_prefix, const char * host, int port, protocol_t protocol, const char * health_endpoint, int verify_ssl)
注册服务（简化版）
向注册表中注册一个服务实例。
Parameters
name 服务名称
path_prefix 路由路径前缀
host 服务主机地址
port 服务端口
protocol 协议类型
health_endpoint 健康检查端点
verify_ssl 是否验证 SSL
Returns
int 0 表示成功，-1 表示失败
Definition at line 77 of file service_registry.c.
References service_register_with_ipv6().
service_register_with_ipv6()
int service_register_with_ipv6 (const char * name, const char * description, const char * path_prefix, const char * host, int port, protocol_t protocol, const char * health_endpoint, int verify_ssl, int is_ipv6)
注册服务（完整版，支持 IPv6）
向注册表中注册一个服务实例，支持 IPv6 地址。
Parameters
name 服务名称
description 服务描述
path_prefix 路由路径前缀
host 服务主机地址
port 服务端口
protocol 协议类型
health_endpoint 健康检查端点
verify_ssl 是否验证 SSL
is_ipv6 是否 IPv6 地址
Returns
int 0 表示成功，-1 表示失败
Definition at line 85 of file service_registry.c.
References service_instance_t::ca_cert_path, service_t::description, service_instance_t::endpoint, g_registry, service_instance_t::health, service_t::health_endpoint, service_instance_t::host, service_t::instance_count, service_t::instances, service_instance_t::ip_addr, service_instance_t::last_check_time, service_t::lock, MAX_SERVICE_INSTANCES, MAX_SERVICES, service_t::name, parse_ip_address(), service_t::path_prefix, service_instance_t::port, service_instance_t::protocol, PROTOCOL_HTTPS, service_instance_t::request_count, SERVICE_HOST_LEN, SERVICE_NAME_LEN, SERVICE_UNKNOWN, and service_instance_t::verify_ssl.
Referenced by handle_service_register(), load_service_config(), and service_register().
service_registry_init()
void service_registry_init (void)
初始化服务注册表
初始化全局服务注册表，包括互斥锁等。
Definition at line 5 of file service_registry.c.
References g_registry.
Referenced by main().
service_select_instance()
service_instance_t * service_select_instance (service_t * service)
选择服务实例（负载均衡）
使用 Round-Robin 算法从服务实例中选择一个。
Parameters
service 服务指针
Returns
service_instance_t* 选中的实例指针
Definition at line 225 of file service_registry.c.
References service_t::current_instance, service_instance_t::health, service_instance_t::host, service_t::instance_count, service_t::instances, service_instance_t::ip_addr, ip_address_t::is_ipv6, service_t::lock, service_t::name, service_instance_t::port, service_instance_t::protocol, PROTOCOL_HTTPS, service_instance_t::request_count, and SERVICE_UNHEALTHY.
Referenced by route_request().
Variable Documentation
g_registry
service_registry_t g_registry
Definition at line 3 of file service_registry.c.
Referenced by handle_get_services(), health_check_callback(), service_deregister(), service_find_by_path(), service_register_with_ipv6(), and service_registry_init().