微服务网关: src/tracer.c File Reference
tracer.c File Reference
#include "gateway.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <uv.h>
Functions
static void generate_random_hex (char *buffer, size_t length)
分布式追踪模块 遵循 W3C Trace Context 标准，兼容 OpenTelemetry
void generate_trace_id (char *trace_id, size_t size)
void generate_span_id (char *span_id, size_t size)
int parse_traceparent (const char *header, char *trace_id, char *parent_span_id, int *sampled)
void build_traceparent_header (char *buffer, size_t size, const char *trace_id, const char *span_id, int sampled)
static int should_sample (void)
void tracing_init_context (client_ctx_t *ctx, const char *incoming_traceparent)
初始化追踪上下文
static void export_to_console (const char *trace_id, const char *span_id, const char *operation, double duration_ms)
static void export_to_http_collector (const char *trace_id, const char *span_id, const char *operation, double duration_ms)
void tracing_export_span (client_ctx_t *ctx, const char *operation, double duration_ms)
导出追踪跨度
void tracing_get_outgoing_traceparent (client_ctx_t *ctx, char *buffer, size_t size)
获取传出追踪上下文
void tracing_add_event (client_ctx_t *ctx, const char *event_name, const char *attributes)
添加追踪事件
Function Documentation
build_traceparent_header()
void build_traceparent_header (char * buffer, size_t size, const char * trace_id, const char * span_id, int sampled)
Definition at line 69 of file tracer.c.
Referenced by tracing_get_outgoing_traceparent().
export_to_console()
void export_to_console (const char * trace_id, const char * span_id, const char * operation, double duration_ms) static
Definition at line 122 of file tracer.c.
Referenced by tracing_export_span().
export_to_http_collector()
void export_to_http_collector (const char * trace_id, const char * span_id, const char * operation, double duration_ms) static
Definition at line 130 of file tracer.c.
References g_gateway_config, and log_debug().
Referenced by tracing_export_span().
generate_random_hex()
void generate_random_hex (char * buffer, size_t length) static
分布式追踪模块 遵循 W3C Trace Context 标准，兼容 OpenTelemetry
Definition at line 16 of file tracer.c.
Referenced by generate_span_id(), generate_trace_id(), and tracing_init_context().
generate_span_id()
void generate_span_id (char * span_id, size_t size)
Definition at line 34 of file tracer.c.
References generate_random_hex().
Referenced by tracing_get_outgoing_traceparent(), and tracing_init_context().
generate_trace_id()
void generate_trace_id (char * trace_id, size_t size)
Definition at line 27 of file tracer.c.
References generate_random_hex().
Referenced by tracing_init_context().
parse_traceparent()
int parse_traceparent (const char * header, char * trace_id, char * parent_span_id, int * sampled)
Definition at line 42 of file tracer.c.
Referenced by tracing_init_context().
should_sample()
int should_sample (void) static
Definition at line 78 of file tracer.c.
References g_gateway_config.
Referenced by tracing_init_context().
tracing_add_event()
void tracing_add_event (client_ctx_t * ctx, const char * event_name, const char * attributes)
添加追踪事件
在当前跨度中添加事件标记。
Parameters
ctx 客户端上下文
event_name 事件名称
attributes 事件属性（JSON 格式）
Definition at line 189 of file tracer.c.
References g_gateway_config, client_ctx_t::is_sampled, and log_debug().
tracing_export_span()
void tracing_export_span (client_ctx_t * ctx, const char * operation, double duration_ms)
导出追踪跨度
在请求完成时导出追踪数据到 Jaeger/Zipkin 等后端。
Parameters
ctx 客户端上下文
operation 操作名称
duration_ms 操作持续时间（毫秒）
Definition at line 154 of file tracer.c.
References export_to_console(), export_to_http_collector(), g_gateway_config, client_ctx_t::is_sampled, client_ctx_t::span_id, and client_ctx_t::trace_id.
Referenced by on_write_completed().
tracing_get_outgoing_traceparent()
void tracing_get_outgoing_traceparent (client_ctx_t * ctx, char * buffer, size_t size)
获取传出追踪上下文
生成用于向后端服务发起请求的 traceparent。
Parameters
ctx 客户端上下文
buffer 输出缓冲区
size 缓冲区大小
Definition at line 174 of file tracer.c.
References build_traceparent_header(), g_gateway_config, generate_span_id(), client_ctx_t::is_sampled, and client_ctx_t::trace_id.
Referenced by forward_to_service().
tracing_init_context()
void tracing_init_context (client_ctx_t * ctx, const char * incoming_traceparent)
初始化追踪上下文
从请求头解析 traceparent，或生成新的追踪 ID。
Parameters
ctx 客户端上下文
incoming_traceparent 传入的 traceparent 字符串
Definition at line 92 of file tracer.c.
References g_gateway_config, generate_random_hex(), generate_span_id(), generate_trace_id(), client_ctx_t::is_sampled, log_debug(), parse_traceparent(), client_ctx_t::request_id, should_sample(), client_ctx_t::span_id, and client_ctx_t::trace_id.
Referenced by on_new_connection().