微服务网关: src/utils.c File Reference
utils.c File Reference
#include "gateway.h"
Functions
void * pool_alloc (client_ctx_t *ctx, size_t size)
从内存池分配内存
char * get_query_param (client_ctx_t *ctx, const char *key)
获取查询参数
Function Documentation
get_query_param()
char * get_query_param (client_ctx_t * ctx, const char * key)
获取查询参数
从 URL 查询字符串中提取指定参数的值。
Parameters
ctx 客户端上下文
key 参数名
Returns
char* 参数值（栈内存，生命周期同请求）
Definition at line 24 of file utils.c.
References pool_alloc(), and client_ctx_t::url.
Referenced by handle_get_employees().
pool_alloc()
void * pool_alloc (client_ctx_t * ctx, size_t size)
从内存池分配内存
从连接的内存池中分配指定大小的内存。 如果池空间不足，回退到 malloc。
Parameters
ctx 客户端上下文
size 需要的字节数
Returns
void* 分配的内存指针
Definition at line 5 of file utils.c.
References mem_pool_t::data, client_ctx_t::pool, POOL_SIZE, and mem_pool_t::used.
Referenced by get_query_param().